### ISSUE TITLE
Create favicon

### ISSUE THREAD

**Issue by vitorbaptista** [vitorbaptista/shellshare#20]

**Comment by ltartari** [comment]
![favicon](https://cloud.githubusercontent.com/assets/114248/10587004/f4cdac88-767d-11e5-921f-4bcb61a4978d.png)
 @vitorbaptista , how about this to start with?

**Comment by ltartari** [comment]
Using https://www.shareaholic.com/openshareicon?PHPSESSID=0fd6b34ae9881836b83a622270c485aa as inspiration : )

**Comment by vitorbaptista** [comment]
@ltartari Didn't know about the OpenShareIcon. Looks interesting, but I it feels too crowded IMO, and although the dollar sign is a nice touch (to represent the shell), I think it's too small to be seen. I was thinking along the lines of a small terminal (more obvious), or maybe a `$_`, to be clearer that it's not about money :smile: 

What do you think?

**Comment by ltartari** [comment]
hahahaha good thinking! let me try that on :stuck_out_tongue:

**Comment by ltartari** [comment]
How do you feel about making the copy green?

![favicon](https://cloud.githubusercontent.com/assets/114248/10593106/9a0231b2-769f-11e5-97b9-381ed1ff3777.png)

**Comment by ltartari** [comment]
Would be really cool to add a blinking one for the live url :wink:

**Comment by ltartari** [comment]
![blink](https://cloud.githubusercontent.com/assets/114248/10593275/edd6cd92-76a0-11e5-9c8f-78677359e58f.gif)

**Comment by vitorbaptista** [comment]
Looks great! Currently, there's no indication that the terminal is being
broadcast (and no way of knowing it, technically speaking), so I can't
implement the blinking icon. But it's a cool idea, and worthy to create
another issue to fix when possible.

I like the icon, I'm just not sure about the green, considering everything
else on the page uses only shades of grey. Do you think it's OK? If so,
please submit a pull request adding the favicon inside the public/images
folder and I'll add the code to use it :+1:

**Comment by vitorbaptista** [comment]
Correcting myself: add the favicon into `./public` instead
