### ISSUE TITLE
Macbooks doesn't have wget by default

### ISSUE THREAD

**Issue by vitorbaptista** [vitorbaptista/shellshare#24]
In Mac OS, curl is installed by default (and wget not); in Ubuntu, it's the other way around. Given this, we need different instructions for Mac and Linux.

**Comment by vitorbaptista** [comment]
@ltartari what do you think of the UI? Too hidden?

![shellshare](https://cloud.githubusercontent.com/assets/76945/10645238/aa18c6c0-7824-11e5-9cb6-c2ad103515ab.png)

**Comment by ltartari** [comment]
They could be located at the top, since they have a behaviour similar to tabs (controlling the content below it).

Maybe make it pop a bit more… the Mac OS one looks disabled in the pic.

**Comment by vitorbaptista** [comment]
I tried at the top, but couldn't find a placement I enjoyed. At least not with them with this size. 

About the colors: great! The Mac OS is disabled in the screenshot :smile:

These changes are deployed already, if you'd like to take a look.

**Comment by vitorbaptista** [comment]
Closing this for now, but feel free to reopen it
