### ISSUE TITLE
Improve SEO

### ISSUE THREAD

**Issue by vitorbaptista** [vitorbaptista/shellshare#26]

**Comment by vitorbaptista** [comment]
@ltartari do you have a high-resolution image of the site's icon to add as its OpenGraph's image? 128x128 should be enough.

**Comment by ltartari** [comment]
Yes. Currently it is a Sketch file (which is similar to an SVG; I can export to an SVG and leave it inside the project if you want).

It can be resized to any need:
![opengraphicon](https://cloud.githubusercontent.com/assets/114248/10665368/718db81c-78a9-11e5-8a74-7c6b084dcf6b.png)
