### ISSUE TITLE
Add space before the semi colon to install snippet

### ISSUE THREAD

**Issue by amercader** [vitorbaptista/shellshare#29]
If you copy the current linux install instruction:
```
wget -qO shellshare http://get.shellshare.net; python shellshare
```

... and paste it into the terminal you get the semicolon as part of the URL (at least on zsh):

```
> wget -qO shellshare http://get.shellshare.net\; python shellshare
```
This will download an empty shellshare file and nothing will happen.

If you add a space then it works fine:

```
wget -qO shellshare http://get.shellshare.net ; python shellshare
```

**Comment by vitorbaptista** [comment]
Thanks for the report, @amercader. I changed the `;` for `&&`, which fixes this and is better overall (as python is only executed if the downloading is successful).

:beers:

**Comment by amercader** [comment]
Cheers mate
