### ISSUE TITLE
Broken pipe when trying to connect to a already full of output terminal

### ISSUE THREAD

**Issue by clodbrasilino** [vitorbaptista/shellshare#30]
I just realized that, when trying to connect to a terminal that had already a quite big output before connecting, the web client simply does not show the whole output from the terminal and I receive a 'broken pipe' unhandled exception at the shell.

There's a lot of output between the two terminal screenshots. That's about 50KB+ data.

<img width="1440" alt="shellshare terminal 1" src="https://cloud.githubusercontent.com/assets/886522/10672024/ff61e950-78c3-11e5-81cd-bdeab3dd2a05.png">
<img width="1440" alt="shellshare terminal 2" src="https://cloud.githubusercontent.com/assets/886522/10672023/ff5d8310-78c3-11e5-91d6-c8e4729e473a.png">

![shellshare web](https://cloud.githubusercontent.com/assets/886522/10672025/ff6c852c-78c3-11e5-9a1f-0a62ed3b8a58.png)

**Comment by vitorbaptista** [comment]
I'd guess this is solved by https://github.com/vitorbaptista/shellshare/pull/35. If not, please reopen.
