### ISSUE TITLE
Create package for homebrew

### ISSUE THREAD

**Issue by vitorbaptista** [vitorbaptista/shellshare#31]
Related to #28 

Writing a homebrew package seems quite easy as well (check https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Formula-Cookbook.md), and the packages are managed through GitHub. I don't have a Mac to write it, though. If you have some time, this would be a great contribution.

**Comment by Haroenv** [comment]
It seems like you can set it up on a non-mac too, but I didn't quite understand the documentation while skimming through it, might make time for it later though.

**Comment by vitorbaptista** [comment]
Sounds interesting, @Haroenv. Didn't know that Homebrew worked on Linux as well. If you find some time to work on it, please go ahead :smile:

**Comment by arthar360** [comment]
I have a mac, and I am trying to figure out how to add this to homebrew. I will need your help to make it work as I am not understanding few things in the brew documentation.

**Comment by vitorbaptista** [comment]
@arthar360 Sure, happy to help as I can. What issues are you facing?

**Comment by arthar360** [comment]
@vitorbaptista Homebrew Furmula is setup but PR was rejected. Have a look at https://github.com/Homebrew/homebrew-core/pull/10438

**Comment by arthar360** [comment]
@vitorbaptista We are live on homebrew! :) https://github.com/Homebrew/homebrew-core/pull/10518
Time for `brew install shellshare`

**Comment by arthar360** [comment]
<img width="1099" alt="screen shot 2017-03-04 at 4 16 36 pm" src="https://cloud.githubusercontent.com/assets/7428184/23578132/03904132-00f6-11e7-8c6c-41aa15c68093.png">

**Comment by vitorbaptista** [comment]
Yay!!! Thanks a lot for your contribution, @arthar360. I'll update our readme to add the option of installing through `brew`.
