### ISSUE TITLE
Not working in Ubuntu 16.04

### ISSUE THREAD

**Issue by hchaithanya** [vitorbaptista/shellshare#42]
Shellshare is not working in Ubuntu 16.04. The commands are getting executed and it does not give me any link.

**Comment by vitorbaptista** [comment]
@hchaithanya I just tested on Ubuntu 16.04 and it worked fine. Did you receive any error messages?

**Comment by hchaithanya** [comment]
Previously, the command did not return me anything,  and I have resolved it now. Thanks!

**Comment by vitorbaptista** [comment]
@hchaithanya Glad it's working. Did you do anything to solve it?
