### ISSUE TITLE
Getting handshake failure

### ISSUE THREAD

**Issue by arthar360** [vitorbaptista/shellshare#43]
I am always getting this error when I try to run

**$ python shellshare** 

I get 

> Sharing terminal in https://shellshare.net/r/dRulMy0OrKeBXSlSxH
> bash-3.2$ Unhandled exception in thread started by <function stream_file at 0x10610a410>
>     Traceback (most recent call last):
>                                         File "shellshare", line 80, in stream_file
>                                                                                       success = post(conn, url, encoded_str, room, password)
>                                                           File "shellshare", line 61, in post
>              raise e
>                     ssl.SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:590)

The shell is not broadcasted.

Versions:
Mac OS X Yosemite 10.10.5
shellshare 1.0.0

**Comment by vitorbaptista** [comment]
Hi @arthar360, what's your Python version?

**Comment by arthar360** [comment]
Hi @vitorbaptista,  it's Python 2.7.10

**Comment by vitorbaptista** [comment]
@arthar360 Does it still work if you get the newest code? (i.e. `wget -qO shellshare https://get.shellshare.net && python shellshare`)

I can't reproduce it locally with the same Python version as yourself. From what I've read, this error means that Shellshare's servers and your local machine couldn't agree on a cipher to use. I don't have access to a Mac OS X machine, but I've done some checks on shellshare's SSL certificate (LetsEncrypt) and everything seemed fine.

**Comment by arthar360** [comment]
I removed the file and again did `wget -qO shellshare https://get.shellshare.net && python shellshare`
But facing same issue. My Linux System (CentOS 7.2) runs it flawlessly. 

There seems no verbose debugging mode (usually -vvv type) here. Any method to get the verbose output?

**Comment by vitorbaptista** [comment]
@arthar360 I found this issue that have a solution that might solve it: https://github.com/kennethreitz/requests/issues/3340

If I check the openssl versions on my machine, I get:
```bash
$ openssl version
OpenSSL 1.0.2g  1 Mar 2016
$ python2.7 -c "import ssl; print(ssl.OPENSSL_VERSION)"
OpenSSL 1.0.2g  1 Mar 2016
```

Could you do the same? It's possibly a case of either upgrading your openssl and/or reinstalling python (to use the newer openssl version)

**Comment by arthar360** [comment]
Thanks @vitorbaptista. I was able to solve this.

# The Problem
```
$openssl version
OpenSSL 0.9.8zg 14 July 2015
```

The OpenSSL version apple provides is quite old. Even when my system is up to date, It seems Apple isn't providing updates for openssl. One of the errors I started receiving while using brew is **Apple has deprecated use of OpenSSL in favor of its own TLS and crypto libraries**


# The Solution

Upgrading the openssl.


```
#Install Homebrew if not installed
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

#Update brew
brew update

#Install openssl ( This might give some errors, you can ignore them)
brew install openssl

#Renaming the openssl command to openssl_default so that we can link the new openssl (from homebrew) at /usr/bin/openssl
sudo mv /usr/bin/openssl /usr/bin/openssl_default 

#Linking latest openssl binary - Make sure you choose the latest version. Latest as of now is 1.0.2k
sudo ln -s /usr/local/Cellar/openssl/1.0.2k/bin/openssl /usr/bin/openssl
```
```
#Checking OpenSSL version
openssl version
OpenSSL 1.0.2k  26 Jan 2017
```

I rebooted the machine so that python notices the change. And now broadcast is working.

**Comment by vitorbaptista** [comment]
Thanks @arthar360! I'm happy you're able to fix it.
