### ISSUE TITLE
no module named httplib (cannot run shellshare)

### ISSUE THREAD

**Issue by edmundlaugasson** [vitorbaptista/shellshare#47]
Running 64-bit UbuntuServer 16.04.2 LTS and [python 3.5.1](http://packages.ubuntu.com/search?keywords=python3&searchon=names&suite=xenial&section=all)

trying to run the shellshare:
`python3 shellshare`
or
`python3 shellshare --room MY-ROOM --password MY-PASS`

... and getting the following error message:
```
Traceback (most recent call last):
  File "shellshare", line 7, in <module>
    import httplib
ImportError: No module named 'httplib'
```

Using python3 and tried to install:
`sudo apt update && sudo apt install python3-httplib2 -y && sudo apt clean`
... but no success... Did even restart the machine after installing that package but did not help either.

There are the following packages available:
```
$ apt search httplib
python-httplib2
python3-httplib2

```

**Comment by vitorbaptista** [comment]
@edmundlaugasson Thanks for the report! There were a few other issues regarding py3 support, fixed on https://github.com/vitorbaptista/shellshare/commit/5f2cde01b1a51facbebf3caf53aeec11d11189b4. I already deployed version 1.0.2 that fixes this. Please download the new version and let me know if this solves your issues.

Feel free to reopen this issue (or open a new one) if you face some problem.
