### ISSUE TITLE
feature request: show text highlighting also online

### ISSUE THREAD

**Issue by edmundlaugasson** [vitorbaptista/shellshare#48]
When marking text by holding down mouse left key and dragging over text by highlighting it - would be possible to show it also in broadcast? It would be extremely useful when teaching and would like to highlight the exact part of text what is under discussion.

**Comment by vitorbaptista** [comment]
@edmundlaugasson Unfortunately, I don't think that's possible. However, you can highlight using tmux, or an editor like vim/emacs, and shellshare will pick it up just fine. The problem is highlighting with the mouse.
