### ISSUE TITLE
Terminal size is too big.

### ISSUE THREAD

**Issue by amosbird** [vitorbaptista/shellshare#49]
I'm getting this error
```
Current terminal size is 55x239.
It's too big to be viewed on smaller screens.
You can resize it anytime.
```
when running `shellshare`. And the web terminal looks weird. How can I make it adjust to current size with scroll bars?

It looks like this ![](https://paste.wentropy.com/5oHF.png)

**Comment by vitorbaptista** [comment]
@amosbird You need to resize your terminal's screen. It should automatically update the UI on shellshare.net. Feel free to reopen this issue if that doesn't solve your problem.

**Comment by amosbird** [comment]
Well I cannot resize my terminal, it's my main working ground which I need it to be wide.

**Comment by vitorbaptista** [comment]
@amosbird Unfortunately, that's currently the only solution. I created issue #50 to display a horizontal scrollbar instead of breaking the lines. If you have time, I'd appreciate some help. Otherwise, subscribe to that issue to be notified whenever it's fixed :+1:
