### ISSUE TITLE
No output when running command `wget -qO shellshare https://get.shellshare.net && python shellshare`

### ISSUE THREAD

**Issue by khanchi97** [vitorbaptista/shellshare#52]
I am not getting any output when running given command on my machine Gnome Ubuntu 16.04.

**Comment by vitorbaptista** [comment]
Could you try  `wget -O shellshare https://get.shellshare.net && python shellshare` and share the output? I ran it locally and everything seems fine. Maybe you got unlucky and tried it when the servers were down for a moment?

**Comment by khanchi97** [comment]
Ok, here is the output:
➜  ~   wget -O shellshare https://get.shellshare.net && python shellshare
--2017-11-15 23:33:06--  https://get.shellshare.net/
Resolving get.shellshare.net (get.shellshare.net)... 104.28.3.224, 104.28.2.224, 2400:cb00:2048:1::681c:3e0, ...
Connecting to get.shellshare.net (get.shellshare.net)|104.28.3.224|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2017-11-15 23:33:07 ERROR 403: Forbidden.

**Comment by vitorbaptista** [comment]
@khanchi97 Sorry for the super late reply. Are you still having issues? Shellshare was offline for a while, but it should be now back up and running fine.

**Comment by edmundlaugasson** [comment]
To be honest that happens quite often that shellshare.net is offline. Looks like #44 would give the ability to run without server.

**Comment by vitorbaptista** [comment]
Closing this now as there haven't been updates in a while. Feel free to reopen if you still face this issue.
