### ISSUE TITLE
shellshare.net is down

### ISSUE THREAD

**Issue by devnoname120** [vitorbaptista/shellshare#53]
![image](https://user-images.githubusercontent.com/2824100/33686150-39815192-dad4-11e7-8327-e8262a7ad275.png)

**Comment by vitorbaptista** [comment]
Thanks for the report, I'm working on it. Everything should be back up by this week. Sorry for the inconvenience this might have caused.

**Comment by devnoname120** [comment]
Thanks a lot!

**Comment by vitorbaptista** [comment]
@devnoname120 We're back online. I also added a uptime monitor, as I should have done a long time ago, so I can react quicker if/when shellshare goes down again.
