### ISSUE TITLE
Add topic: terminal-share

### ISSUE THREAD

**Issue by katrinleinweber** [vitorbaptista/shellshare#59]
Thanks for publishing this! How about adding it to [GitHub.com/topics/terminal-share](https://github.com/topics/terminal-share) alongside similar tools by [adding that topic](https://help.github.com/articles/about-topics/) to this repo? Thank you :-)

**Comment by vitorbaptista** [comment]
Good point! Added. Thanks for the recommendation.

**Comment by katrinleinweber** [comment]
Merci :-)
