### ISSUE TITLE
Write README

### ISSUE THREAD

**Issue by vitorbaptista** [vitorbaptista/shellshare#7]
Ideally, the install process will be in the lines:

    curl get.shellshare.net -O shellshare

We need script (or ttyrec) now, but we should keep it as simple as possible. If we fix #2, this might be all :smiley:

**Comment by ltartari** [comment]
- [ ] How to setup the project environment @vitorbaptista

**Comment by ltartari** [comment]
- [ ] List project dependencies @vitorbaptista
